### ISSUE TITLE
Team Charter

### ISSUE THREAD

**Issue by CallumChalmers29** [CallumChalmers29/crispy-disco#1]
Looking for feedback on my team charter

**Comment by dvasques83** [comment]
The team charter for the Operation Safe Cracker is very clear. I was written in a straightforward manner, pointing out explicitly what the project is about. I would perhaps try to develop a little more the success criteria, trying to get more metrics based on the functionalities of the proposed tool.

**Comment by CallumChalmers29** [comment]
Thanks for your feedback - that is a good suggestion and I will make those changes once I meet with my supervisor and we discuss the finer details of the software. I had a look at your Team Charter in your repo and saw some good examples of what you mean. I think after this week's class I will understand a bit more about how to break the project down into smaller pieces.

**Comment by CallumChalmers29** [comment]
Hi @dvasques83, I know this was a long time ago but I was wondering if you give my Team Charter a final check so we can close this issue

Thanks
Callum

**Comment by dvasques83** [comment]
Sure, let's do it:

1- In Project Mission, I think should be nice to put in () what is SNP
2- In Success Criteria, maybe update the submission date?

Other than that it looks beautiful to me.
Nice work!

**Comment by CallumChalmers29** [comment]
Hi Demi

Great feedback, I have included those changes and you can seem them [here](https://github.com/CallumChalmers29/CallumChalmers29-crispy-disco/blob/master/assignments/medsci736-teamcharter-ccha939-2.md) for the final sign off :)

Thanks again 
Callum

**Comment by dvasques83** [comment]
All good! From my point of view, you can close the issue.
Cheers!
